---
title: Home
author:
output:
 html_document:
  toc: true
  toc_depth: 6  				# upto three depths of headings (specified by #, ## and ###)
  number_sections: false 	# if you want number sections at each table header
  theme: default  		# default, cerulean, journal, flatly, darkly, readable, spacelab, united, cosmo, lumen, paper, sandstone, simplex, and yeti
  highlight: tango  		# specifies the syntax highlighting style
urlcolor: gray
citecolor: gray
---

```{r set-options, echo=FALSE, cache=FALSE}
options(width = 150)
```

```{r setup, include = F}
knitr::opts_chunk$set(echo = T)
```

<style type="text/css"> /* This sets the overall width of the HTML page */
.main-container {
  max-width: 670px;
  margin-left: auto;
  margin-right: auto;
};
p {line-height: 4em;}
</style>




<hr>

<a href="karmabad-o-punorjonmobad.html">কর্মবাদ ও পুনর্জন্মবাদ</a>

<a href="sriramakrishna-vidyasagar-conversation.html">শ্রীরামকৃষ্ণের সঙ্গে শ্রী ঈশ্বরচন্দ্র বিদ্যাসাগরের কথোপকথন</a>




<hr><br>

```{r, eval = F, include = F}
	# Create Rmd html result
	rm(list=ls())
	dir = "/Users/nsanyal/Documents/GitHub/nilotpalsanyal.github.io/"
	setwd(dir)
	library(rmarkdown)
	render( input="index.Rmd" )
```













