---
title: "Sanskrit words sounding close to some familiar English words"
author: "Nilotpal Sanyal  \n\n [https://nilotpalsanyal.github.io](https://nilotpalsanyal.github.io)"
output: 
 html_document:
  # code_folding: show
  toc: FALSE
  toc_depth: 3           
  toc_float: FALSE
  number_sections: no   
  # theme: united     
  highlight: tango     
urlcolor: blue
citecolor: blue
---

<!-- # set the overall width of the HTML page -->
<style type="text/css"> /* This sets the overall width of the HTML page */
  .main-container {
    max-width: 800px;   
    margin-left: auto;
    margin-right: auto;
  }
  body, td {
     font-size: 16.5px;
     /*font-family: Calibri;*/
     background: rgb(250,250,250);
  }
  code.r{                   /*for r code*/
    font-size: 16.5px;
  }
  pre {                 /*for output of knitr chunks*/
    font-size: 16.5px
    border: 0;
  }
</style>


$$\\[5px]$$

**H**ere are some familiar English words that sound close to Sanskrit words having mostly similar meaning. I will not go into the debate whether these Sanskrit words are the root of these English words, or simply cognates of these English words through the hypothesized [Proto Indo-European (PIE)](https://en.wikipedia.org/wiki/Proto-Indo-European_language) language, or neither. I am not an academic expert in [comparative linguistics](https://en.wikipedia.org/wiki/Comparative_linguistics) or [philology](https://en.wikipedia.org/wiki/Philology) although possessing keen interest in them. I will simply leave it on the readers to do their own research and come up with intuitions about the state of things. However, it is tough to deny the sense of similarity that strikes the mind on reading these words and corresponding Sanskrit words.

- The list is compiled using this [website post](https://www.hitxp.com/articles/linguistics/english-loan-words-list-sanskrit-latin-greek-persian/) which has generated a long list of interested comments. 
- Another informative chain of discussions on this issue is [here](https://www.quora.com/How-do-we-know-that-a-Proto-Indo-European-language-really-existed-What-is-the-evidence).
- Finally, you can consult the [Online Etymology Dictionary](https://www.etymonline.com).

With this, let us take a look at the words. 


<hr><hr>

<!-- <p>&nbsp;</p> -->


| Category              | Sanskrit word           |                         | Latin(L) / Greek(G) / Arabic(A) / Proto Germanic(PGE) word | English word           | English meaning |
|-----------------------|-------------------------|-------------------------|----------------------------------------------------------------------|--------------------------------|-----------------|
|                       | Bengali transliteration | English transliteration |                                                                      |                                |                 |
| Numbers               | শূন্য                   | Shunya                  | Cipher (A)                                                           | Zero                           | zero            |
|                       | ত্রি                    | Tri                     | Treis (G)                                                            | Three                          | three           |
|                       | চতুর্                   | Chatur                  | Quartus (L)                                                          | Quarter                        | four            |
|                       | পঞ্চ                    | Pancha                  | Pente (G)                                                            | Penta, Five                    | five            |
|                       | সপ্ত                    | Sapta                   | Septum (L)                                                           | Seven                          | seven           |
|                       | অষ্ট                    | Ashta                   | Octo (L)                                                             | Eight                          | eight           |
|                       | দশ                      | Dasha                   | Deca (G)                                                             | Deca                           | deca            |
| Pronouns              | তৎ                      | Tat                     | Talis (L)                                                            | That                           | that            |
|                       | ত্বম্                   | Tvam                    | Dih                                                                  | Thee                           | you             |
| Verbs                 | জন্                     | Jan                     | Genea (G)                                                            | Gene                           | to take birth   |
|                       | কৃ                      | Kri                     | Creatus (L)                                                          | Create                         | to do           |
|                       | স্মি                    | Smi                     | Smilen (L)                                                           | Smile                          | to smile        |
|                       | বম                      | Vama/Vamati             | Vomere (L)                                                           | Vomit                          | to vomit        |
|                       | স্থ                     | SthaH                   | Stare (L)                                                            | Stay                           | situated        |
|                       | লুভ                     | Lubh                    | Lubo (L and PGE)                                                     | Love                           | to desire       |
| Relations             | মাতৃ                    | Matr                    | Mater (L)                                                            | Mother                         |                 |
|                       | পিতৃ                    | Pithr                   | Pater (L)                                                            | Father                         |                 |
|                       | ভ্রাতৃ                  | Bhrathr                 | Phrater (G)                                                          | Brother, Fraternal             |                 |
|                       | সুনূ                    | Sunu                    | Sunu (GE)                                                            | Son                            |                 |
|                       | দুহিতৃ                  | Duhitr                  |                                                                      | Daughter                       |                 |
| Body parts            | নাসা                    | Naasaa                  | Nasus (L)                                                            | Nose                           | Nose            |
|                       | দন্ত                    | Danta                   | Dentis (L)                                                           | Dental                         | Tooth           |
|                       | পাদ                     | Paad                    | Pedis (L)                                                            | Ped as in Pedestrian, Pedestal | Foot            |
|                       | জানু                    | Jaanu                   | Genu (L)                                                             | Knee                           | Knee            |
|                       | হৃৎ                     | Hrt                     | Herto (PGE)                                                          | Heart                          | Heart           |
|                       | নাড়ি                   | Nari                    | Nervus (L)                                                           | Nerve, Nervous                 | Nerve           |
|                       | কফ                      | Kapha                   | Coughen                                                              | Cough                          | Mucus           |
| Tastes                | শর্করা                  | Sharkara                | Succarum                                                             | Sugar                          | Sugar / Sucrose |
|                       | স্বাদ                   | Svaad                   | Suavis (L)                                                           | Taste                          | Sweet           |
| Animals               | গৌ                      | Gau                     | Bous (G)                                                             | Cow                            | Cow             |
|                       | সর্প                    | Sarpa                   | Serpentem (L)                                                        | Serpent                        | Snake           |
|                       | মক্ষিকা                 | Makshikaa               | Musca (L)                                                            | Mosquito                       | Fly             |
|                       | মুষ                     | Mush                    | Mus (L)                                                              | Mouse                          | Mouse           |
|                       | শৃগাল                   | Srgalah                 | Shagal (Persian)                                                     | Jackal                         | Jackal          |
| Fruits, Plants, Trees | নারঙ্গি                 | Narangi                 | Naranj                                                               | Orange                         | Orange          |
|                       | পিপ্পল                  | Pippali                 | Piperi (G)                                                           | Pepper                         | Pepper          |
|                       | চন্দন                   | Chandana                | Santalon (G)                                                         | Sandalwood                     | Sandalwood      |
| Stones                | মরগরুম                  | Maragadum               | Smaragdus (L)                                                        | Emerald                        | Emerald         |
|                       | নীল                     | Nila                    | Nilak (Persian)                                                      | Lilac                          | Dark Blue       |
|                       | উপল                     | Upalah                  | Opalus (L)                                                           | Opal                           | Precious stone  |
|                       | অর্জুন                  | Arjuna                  | Argentinum (L)                                                       | Argentum                       | Charm of Silver |
| Nature                | নক্ত                    | Nakta                   | Nocturnalis (L)                                                      | Nocturnal                      | Night           |
|                       | চন্দ্র                  | Chandra                 | Candela (L)                                                          | Candle                         | Moon            |
|                       | অগ্নি                   | Agni                    | Ignis (L)                                                            | Ignite                         | Fire            |
| Miscellaneous         | ধাম                     | Dhama                   | Domus (L)                                                            | Domicile                       |                 |
|                       | দ্বার                   | Dwar                    | Doru                                                                 | Door                           |                 |
|                       | অক্ষ                    | Aksha                   | Axon (G)                                                             | Axis                           |                 |
|                       | নবগাথা                  | Navagatha               | Navigationem (L)                                                     | Navigation                     |                 |
|                       | অনামিকা                 | Anamika                 | Anonymos (G)                                                         | Anonymous                      |                 |
|                       | নাম                     | Naama                   | Nomen (L)                                                            | Name                           |                 |
|                       | মনু                     | Manu                    |                                                                      | Man/Men/Human                  |                 |
|                       | বর্বর                   | Barbara                 | Barbaria (L)                                                         | Barbarian                      |                 |
|                       | মধ্যম                   | Madhyam                 | Medium (L)                                                           | Medium                         |                 |
|                       | কাল                     | Kaal                    | Kalendae (L)                                                         | Calendar                       |                 |
|                       | মিশ্র                   | Mishra                  | Mixtus (L)                                                           | Mix                            |                 |
|                       | লোক                     | Loka                    | Locus (L)                                                            | Locale                         |                 |
|                       | মহা                     | Maha                    | Magnus (L)                                                           | Mega                           |                 |
|                       | মল                      | Mala                    | Malus (L)                                                            | Malicious, Malformed etc.      |                 |
|                       | মৃত                     | Mrta                    | Mortis (L)                                                           | Murder                         |                 |
|                       | ন                       | Na                      | Ne                                                                   | No                             | no              |
|                       | পর                      | Parah                   | Pera (G)                                                             | Remote                         | far             |
|                       | পথ                      | Patha                   | Pathes (G)                                                           | Path                           | path            |
|                       | রাজা/রায়া              | Raja/Raya               | Regalis (L)                                                          | Ling                           | royal           |
|                       | সম                      | Sama                    | Similis (L), Samaz (PGE)                                             | Same                           | same, similar   |
|                       | বচস্                    | Vachas                  | Vocem (L)                                                            | Speech                         | voice           |
|                       | বহন                     | Vahaami                 | Vehere (L)                                                           | Carry                          | vehicle         |
|                       | বস্ত্র                  | Vastr                   | Vestire (L)                                                          | Cloth                          | vest            |
|                       | যৌবন                    | Yauvana                 | Juvenilis (L)                                                        | Youth                          | youth, juvenile |
|                       | নব                      | Nava                    | Novus (L)                                                            | New                            | nova – new      |
|                       | মিথ্যা                  | Mithya                  | Mythos (G)                                                           | Lie                            | myth            |
|                       | মন                      | Man                     | Mens (L)                                                             | Mind                           | mind            |
|                       | ? বৃহী                  | Vrihis                  | Oriza (L)                                                            | Rice                           | rice            |
|                       | ?                       | Ghas                    | Grasa (GE)                                                           | Grass                          | eat             |
|                       | সমিতি                   | Samiti                  | Committere (L)                                                       | Committee                      | Committee       |
|                       | যান                     | Yaana                   | Wagen (GE)                                                           | Van, Wagon                     | journey, wagon  |
|                       | ?                       | They                    | Dei (GE)                                                             | They                           |                 |
|                       | প্রতি                   | Prati                   | per (L)                                                              | per                            |                 |
|                       | প্রতি শত                | Prati Shat              | per centum (L)                                                       | percent                        |                 |                                                     | percent                        |                 |


$$\\[1in]$$


    




